version: '3.3'
services:
  beesd:
    container_name: beesd
    privileged: true
    restart: unless-stopped
    hostname: beesd
    build:
      context: .
    environment:
      - TZ=Europe/Berlin
      - HASH_TABLE=/mnt/.beeshome/beeshash.dat
      - HASH_TABLE_SIZE=4G
      - OPTIONS=-a -c 1
    volumes:
      - /volume1:/mnt
